services:
    db:
        image: mariadb:latest
        container_name: team13_db
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=team13
        restart: always

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin-team13
        restart: always
        ports:
            - 9090:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password

volumes:
    db_data:
